#!/usr/bin/env node
/**
 * Threader AI - Demo Preparation Script
 *
 * Prepares a demo for a specific company by:
 * 1. Running the scout pipeline to gather fresh data
 * 2. Saving the synthesis to demo-config.json
 * 3. Optionally marking it as public in Supabase
 *
 * Usage: npm run set-demo "CompanyName" [--run-scout]
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import dotenv from 'dotenv';

dotenv.config();

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DEMO_CONFIG_PATH = path.join(__dirname, '../frontend/public/demo-config.json');

/**
 * Parse CLI arguments
 */
function parseArgs() {
  const args = process.argv.slice(2);
  const result = {
    companyName: null,
    runScout: false,
    help: false,
  };

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];

    if (arg === '--help' || arg === '-h') {
      result.help = true;
    } else if (arg === '--run-scout' || arg === '-r') {
      result.runScout = true;
    } else if (!arg.startsWith('-')) {
      result.companyName = arg;
    }
  }

  return result;
}

/**
 * Print help message
 */
function printHelp() {
  console.log(`
╔═══════════════════════════════════════════════════════════════╗
║                  Threader AI - Demo Setup                     ║
╠═══════════════════════════════════════════════════════════════╣
║  Prepare a demo for client outreach                           ║
╚═══════════════════════════════════════════════════════════════╝

Usage:
  npm run set-demo <company_name> [options]

Arguments:
  company_name     Name of the company for the demo (required)

Options:
  --run-scout, -r  Run the scout pipeline to gather fresh data
  --help, -h       Show this help message

Examples:
  npm run set-demo "Linear"           # Quick setup with sample data
  npm run set-demo "Figma" --run-scout  # Full pipeline with fresh data

After running this command:
  1. Start the frontend: cd frontend && npm run dev
  2. Share the demo link: http://localhost:5173?company=Linear
`);
}

/**
 * Load existing demo config
 */
function loadDemoConfig() {
  try {
    if (fs.existsSync(DEMO_CONFIG_PATH)) {
      const content = fs.readFileSync(DEMO_CONFIG_PATH, 'utf-8');
      return JSON.parse(content);
    }
  } catch (error) {
    console.warn('[set-demo] Could not load existing config:', error.message);
  }
  return { companyName: null, synthesis: null, lastUpdated: null };
}

/**
 * Save demo config
 */
function saveDemoConfig(config) {
  const configWithMeta = {
    ...config,
    lastUpdated: new Date().toISOString(),
    note: "Auto-generated by 'npm run set-demo'. Set synthesis to null to use sample data.",
  };

  fs.writeFileSync(DEMO_CONFIG_PATH, JSON.stringify(configWithMeta, null, 2));
  console.log(`[set-demo] Saved demo config to ${DEMO_CONFIG_PATH}`);
}

/**
 * Run the scout pipeline (if --run-scout flag is provided)
 */
async function runScoutPipeline(companyName) {
  console.log(`\n[set-demo] Running scout pipeline for "${companyName}"...`);
  console.log('[set-demo] This may take a few minutes.\n');

  try {
    // Dynamically import the scout pipeline
    const { runPipeline } = await import('../src/pipeline.js');

    const results = await runPipeline(companyName, 'demo_tenant', {
      maxItemsPerSubreddit: 30,
      skipStorage: true, // Don't store to Supabase for demo
    });

    if (results.strategicSynthesis) {
      console.log('[set-demo] Scout pipeline completed successfully!');
      return results.strategicSynthesis;
    } else if (results.executiveSummary) {
      console.log('[set-demo] Scout pipeline completed with executive summary.');
      return null; // Will use sample data
    }
  } catch (error) {
    console.error('[set-demo] Scout pipeline failed:', error.message);
  }

  return null;
}

/**
 * Update Supabase public demo record (optional)
 */
async function updateSupabaseDemo(companyName, synthesis) {
  if (!process.env.SUPABASE_URL || !process.env.SUPABASE_SERVICE_ROLE_KEY) {
    console.log('[set-demo] Supabase not configured - skipping database update');
    return;
  }

  try {
    const { createClient } = await import('@supabase/supabase-js');
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_SERVICE_ROLE_KEY
    );

    // Upsert the public demo record
    const { error } = await supabase
      .from('snapshots')
      .upsert({
        tenant_id: 'public_demo',
        company_name: companyName,
        synthesis_data: synthesis,
        is_public: true,
        metadata: { demo: true, updated_by: 'set-demo script' },
        created_at: new Date().toISOString(),
      }, {
        onConflict: 'tenant_id,company_name',
      });

    if (error) {
      console.warn('[set-demo] Supabase update failed:', error.message);
    } else {
      console.log('[set-demo] Updated Supabase public demo record');
    }
  } catch (error) {
    console.warn('[set-demo] Supabase update skipped:', error.message);
  }
}

/**
 * Main function
 */
async function main() {
  const args = parseArgs();

  if (args.help) {
    printHelp();
    process.exit(0);
  }

  if (!args.companyName) {
    console.error('Error: Company name is required\n');
    printHelp();
    process.exit(1);
  }

  console.log(`
╔═══════════════════════════════════════════════════════════════╗
║                  Threader AI - Demo Setup                     ║
╠═══════════════════════════════════════════════════════════════╣
║  Company: ${args.companyName.padEnd(50)}                      ║
╚═══════════════════════════════════════════════════════════════╝
`);

  let synthesis = null;

  // Run scout pipeline if requested
  if (args.runScout) {
    if (!process.env.OPENAI_API_KEY) {
      console.error('[set-demo] OPENAI_API_KEY required for --run-scout');
      console.log('[set-demo] Falling back to sample data...\n');
    } else {
      synthesis = await runScoutPipeline(args.companyName);
    }
  }

  // Save demo config
  const config = {
    companyName: args.companyName,
    synthesis: synthesis,
  };

  saveDemoConfig(config);

  // Update Supabase if configured
  if (synthesis) {
    await updateSupabaseDemo(args.companyName, synthesis);
  }

  // Print success message
  console.log(`
╔══════════════════════════════════════════════════════════════════════════╗
║                    Demo Ready!                                           ║
╠══════════════════════════════════════════════════════════════════════════╣
║  Company: ${args.companyName.padEnd(50)}                                 ║
║  Data:    ${(synthesis ? 'Fresh from scout' : 'Sample data').padEnd(50)} ║
╚══════════════════════════════════════════════════════════════════════════╝

Next steps:
  1. Start the frontend:
     cd frontend && npm run dev

  2. Share the demo link:
     http://localhost:5173?company=${encodeURIComponent(args.companyName)}

  3. For production, deploy and use:
     https://your-domain.com?company=${encodeURIComponent(args.companyName)}
`);
}

main().catch(console.error);
